language: python
env:
  - PIP_VER=1.3.1
  - PIP_VER=latest
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - if [[ $PIP_VER == 'latest' ]]; then pip install --use-mirrors --upgrade pip; else pip install --use-mirrors pip==$PIP_VER; fi
  - pip install -r requirements/tox.txt --use-mirrors
  - pip install coveralls --use-mirrors
# command to run tests
script:
  - py.test --cov reqfiles --cov-report term-missing && flake8 reqfiles
  - flake8 reqfiles
after_success:
  - COVERALLS_REPO_TOKEN=b8EvySSmckK3xv80IOS4ILIKOQIufpwTM coveralls
