language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements/tests.txt --use-mirrors
  - pip install coveralls --use-mirrors
# command to run tests
script: py.test --cov reqfiles --cov-report term-missing
after_success:
  - COVERALLS_REPO_TOKEN=b8EvySSmckK3xv80IOS4ILIKOQIufpwTM coveralls
